name: setup-kosli-cli
description: Install the Kosli CLI on Github Actions runners
inputs:
  version:
    description: Version of Kosli CLI
    required: false
    default: 2.0.0
branding:
  icon: download-cloud
  color: blue
runs:
  using: node16
  main: dist/index.js
